language: node_js
node_js:
- node
before_script:
- cd back-end
- npm i nyc
script:
- npm test
env:
  global:
    secure: fJCugPl2YFJcEwOKZ2tWBPzEe1aKKL6m7A7WtD5gxncrAKeK5+3y8i5yTJ6FEiOuQHIRiWK4T159YRm+JxU6ssZ9ZKthA/CBgGuV15gjxsB8oMRO36c9BwTdHvSg9xnFmoTKDvC9mcawfvQWt4eNBp34jWhwroQ8zK4qlhiFlm0epVFz1D6F+5Gr6B8MNfhJ6nVRfLjRregdwXFzwY16q4iOJ1PNUA62q2No4JEeICbOZygAfTh1bKxRB1uexTv0ZQtGwMFFKRtOiFxcA0bDUnejMJCnTO1S29NXCA4Sqe8c39VmhlARmsfuzLkVj9LPr+pNDS5pLUUzAijwt/DzD5pRE1Upix8HNRIa9AbHvVX5b5sSFB9q+zlD+KsYJoEf4YQgTrwjHBrryixZad4Si/Lh3ShrscVM00i8wQzappXo/MbrADmkJiJFgXtSBiDAkN97h3nxRCJfYhde48KWscngYb1B7jaLsgrnLpsY47w37yiLUQQP7x5d30Oo70LqZMEZL/HivLiU/Sw0EdFKY/D1o6MBzirA/p9g6aX55M8NKdoHGT0S5nSRVNVfCvENZs41SGqvASaem5RhXFCGqfljQst4VtRk8DBwJz1pBQMReia10daB2eira72WELnWvChLrxcY+rZ5E/zFFLJtTjVlPmd+916EIvUSYS1Zxys=
