name: Continuous Integration for RecipeBox

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
        DB_PASS: ${{ secrets.DB_PASS }}
        DB_USER: ${{ secrets.DB_USER }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        ORIGIN: ${{ secrets.ORIGIN }}
        RBXPASS: ${{ secrets.RBXPASS }}
        REACT_APP_ORIGIN: ${{ secrets.REACT_APP_ORIGIN }}

    steps:
      - name: Install dependencies and run unit tests
        run: |
          npm install
          npm i nyc
          npm test
        working-directory: ./back-end