name: Continuous Integration for RecipeBox

on: [push]
jobs: 
  runs-on: ubuntu-latest

  strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

  steps:
    env:
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_USER: ${{ secrets.DB_USER }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      ORIGIN: ${{ secrets.ORIGIN }}
      RBXPASS: ${{ secrets.RBXPASS }}
      REACT_APP_ORIGIN: ${{ secrets.REACT_APP_ORIGIN }}

    - name: Install dependencies and run unit tests
    - run: |
        npm i nyc
        npm test
    working-directory: ./back-end
    with:
        node-version: ${{ matrix.node-version }}